// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID          int64
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	Completed   sql.NullInt64
	CompletedAt sql.NullTime
}
