name: Release

on:
  release:
    types:
      - edited
      - released
      - prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - id: get_version
      name: Get tag version
      uses: jannemattila/get-version-from-tag@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
          go-version-file: "go.mod"

    - name: Build
      run: |
        VERSION=$(echo "${{ steps.get_version.outputs.version }}")
        go build -ldflags "-X terminal-todos/cmd/commands.Version=$VERSION" -o out/bin/cmd/todos_windows.exe ./cmd
        go build -ldflags "-X terminal-todos/cmd/commands.Version=$VERSION" -o out/bin/cmd/todos_linux ./cmd

    - name: Upload artifact todo windows
      uses: actions/upload-artifact@v4
      with:
        name: todos_artifacts
        path: |
          out/bin/cmd/todos_windows.exe
          out/bin/cmd/todos_linux
  
  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download todos artifacts
      uses: actions/download-artifact@v4
      with:
        name: todos_artifacts

    - name: Upload windows
      uses: vesoft-inc/upload-assets@v1.0.0
      with:
        asset-path: "todos_windows.exe"

    - name: Upload Linux
      uses: vesoft-inc/upload-assets@v1.0.0
      with:
        asset-path: "todos_linux"
        
